import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { StaticJsonPokedexRepository } from './infrastructure/http/static-json-pokedex.repository.ts'
import App from './presentation/App.tsx'
import './presentation/i18n/index.ts'
import { PokedexRepositoryProvider } from './presentation/pokedex/PokedexRepositoryProvider.tsx'
import './index.css'

// Composition root of the app: the only place that picks the adapters.
// The Pokédex is generated by `npm run data` into public/data/.
const repository = new StaticJsonPokedexRepository(`${import.meta.env.BASE_URL}data/pokedex.json`)

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <PokedexRepositoryProvider repository={repository}>
      <App />
    </PokedexRepositoryProvider>
  </StrictMode>,
)
