import { useEffect, useState } from 'react'
import type { Dataset } from './types.ts'

type State =
  | { status: 'loading' }
  | { status: 'ready'; dataset: Dataset }
  | { status: 'error'; error: Error }

/** Loads public/data/pokedex.json, generated by `npm run data`. */
export function useDataset(): State {
  const [state, setState] = useState<State>({ status: 'loading' })

  useEffect(() => {
    const controller = new AbortController()
    fetch(`${import.meta.env.BASE_URL}data/pokedex.json`, { signal: controller.signal })
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`)
        return response.json() as Promise<Dataset>
      })
      .then((dataset) => setState({ status: 'ready', dataset }))
      .catch((error: Error) => {
        if (error.name !== 'AbortError') setState({ status: 'error', error })
      })
    return () => controller.abort()
  }, [])

  return state
}
